version: '3'
services:
  raft10:
    image: img.z-chess.arena
    container_name: raft10
    hostname: raft10
    ports:
      - "1883:1883"
    networks:
      endpoint:
        ipv4_address: 192.168.10.110
    extra_hosts:
      - "raft10:192.168.10.110"
      - "raft11:192.168.10.111"
      - "raft12:192.168.10.112"
  raft11:
    image: img.z-chess.arena
    container_name: raft11
    hostname: raft11
    ports:
      - "1884:1883"
    networks:
      endpoint:
        ipv4_address: 192.168.10.111
    extra_hosts:
      - "raft10:192.168.10.110"
      - "raft11:192.168.10.111"
      - "raft12:192.168.10.112"
  raft12:
    image: img.z-chess.arena
    container_name: raft12
    hostname: raft12
    ports:
      - "1885:1883"
    networks:
      endpoint:
        ipv4_address: 192.168.10.112
    extra_hosts:
      - "raft10:192.168.10.110"
      - "raft11:192.168.10.111"
      - "raft12:192.168.10.112"
networks:
  endpoint:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24
          gateway: 192.168.10.1