erupt-app:
  # 登录失败几次，需要验证码
  verifyCodeCount: 2
erupt:
  # 是否开启csrf防御
  csrfInspect: true
  # 是否开启redis方式存储session，默认false，开启后需在配置文件中添加redis配置（同 spring boot）
  redisSession: false
  # 附件上传存储路径, 默认路径为：/opt/erupt-attachment
  uploadPath: /attachment
  # 是否保留上传文件原始名称
  keepUploadFileName: false
  # 登录session时长（redisSession为true时有效）
  upms.expireTimeByLogin: 60
  # 是否记录操作日志，默认true，该功能开启后可在【系统管理 → 操作日志】中查看操作日志
  security.recordOperateLog: true

magic-api:
  web: /magic/web
  # 接口配置文件存放路径
  resource.location: /magic-script
  show-url: true

spring:
  datasource:
    url: jdbc:postgresql://db-pg.isahl.com:5432/isahl.z-chess
    username: isahl.z-chess.pgsql
    password: 2da790253022bd05cddda6d06bdc1e60
  jpa:
    show-sql: true
    generate-ddl: true
    open-in-view: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
#    properties:
#      hibernate:
#        default_schema: "z_chess_referee"
#        format_sql: true
#        enable_lazy_load_no_trans: true
#        hdm2ddl:
#          auto: true
#        jdbc:
#          lob:
#            non_contextual_creation: true
  profiles:
    active: dev
  mail:
    username: xxxx@qq.com
    password: xxxxxxx
    host: smtp.qq.com
    properties:
      mail.smtp.ssl.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.required: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

server:
  port: 9009
  # 启用 gzip 压缩
  compression:
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain
    enabled: true
  error:
    includeException: true
    includeStacktrace: ALWAYS
    includeMessage: ALWAYS