version: '3'
services:
  raft10:
    image: img.z-chess.arena.amd64
    container_name: raft00
    hostname: raft00
    ports:
      - "8080:8080"
      - "8000:8000"
      - "1883:1883"
    networks:
      endpoint:
        ipv4_address: 172.30.10.110
      gate:
        ipv4_address: 172.30.11.110
    extra_hosts:
      - "raft00:172.30.10.110"
      - "raft01:172.30.10.111"
      - "raft02:172.30.10.112"
      - "gate00:172.30.11.110"
    entrypoint: java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000 -jar /app.jar --spring.profiles.active=local
  raft11:
    image: img.z-chess.arena.amd64
    container_name: raft01
    hostname: raft01
    ports:
      - "1884:1883"
      - "8100:8000"
    networks:
      endpoint:
        ipv4_address: 172.30.10.111
    extra_hosts:
      - "raft00:172.30.10.110"
      - "raft01:172.30.10.111"
      - "raft02:172.30.10.112"
      - "gate00:172.30.11.110"
    entrypoint: java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000 -jar /app.jar --spring.profiles.active=local
  raft12:
    image: img.z-chess.arena.amd64
    container_name: raft02
    hostname: raft02
    ports:
      - "1885:1883"
      - "8200:8000"
    networks:
      endpoint:
        ipv4_address: 172.30.10.112
    extra_hosts:
      - "raft00:172.30.10.110"
      - "raft01:172.30.10.111"
      - "raft02:172.30.10.112"
      - "gate00:172.30.11.110"
    entrypoint: java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000 -jar /app.jar --spring.profiles.active=local
networks:
  endpoint:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.10.0/24
          gateway: 172.30.10.1
  gate:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.11.0/24
          gateway: 172.30.11.1