POST http://iot.isahl.com:2808/message/submit?token=290CE476383330D91CBB8DA9849964B24541DBEC207ED398B3A0CBC43FE1BC90
Content-Type: application/json

{
  "topic": "123",
  "content": "hello-client",
  "protocol": "mqtt"
}